package com.gojek.command;

public enum CommandName {

    CREATE_PARKING_LOT,
    PARK,
    LEAVE,
    STATUS,
    REGISTRATION_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBERS_FOR_CARS_WITH_COLOUR,
    SLOT_NUMBER_FOR_REGISTRATION_NUMBER
}
